### ISSUE TITLE
Tracking Issue: Vector Extensions

### ISSUE THREAD

**Issue by chorman0773** [chorman0773/Clever-ISA#1]
This issue is tracking the Vector Extension.

- [ ] Define and Document Vector Instructions
    - [x] Vectorize Scalar Operation prefix
        - [ ] Finalize List of operations that can apply the vector prefix
        - [ ] fcmp, cmp, and btest.
    - [x] Move Vector Operand
    - [x] Bulk Vector Register Storage
    - Any additional instructions that should be included?
- [ ] Review Extension Document
- [ ] Analyze Impact on the Proposed psABI Technical Document

Open Questions:
- [ ] Should atomic operations use the vectorize scalar operation prefix for 16-byte values, or should separate instructions (like `vmov`) be created?
    - [ ] xchg, cmpxchg, and wcmpxchg do not inspect the vector element size field of the prefix, unlike other modified instructions, but like `vmov` (opcode 0x401). 
- [ ] How to extract flags results other than M, Z, and P, and flags results for individual vector elements?

**Comment by chorman0773** [comment]
Finalization Blocked on #4
