### ISSUE TITLE
Tracking Issue: Main ISA

### ISSUE THREAD

**Issue by chorman0773** [chorman0773/Clever-ISA#2]
This issue is tracking progress on the main ISA specification.

- [ ] Registers
    - [x] Define Register List
    - [x] Review User Register List
    - [ ] Review Supervisor Register List
    - [ ] Finalize Base Register List  
- [ ] Operand Encoding
    - [x] Define Operand Encoding
    - [ ] Review Operand Encoding
    - [ ] Finalize Operand Encoding
- [ ]  Instructions
     - [x] Instruction Encoding 
     - [ ] Program Instructions
         - [x] Define Instruction List
         - [ ] Review Instruction LIst
         - [ ] Finalize Instruction List
     - [ ] Supervisor Instructions
         - [x] Define Instruction List 
         - [ ] Review Instruction List
         - [ ] Finalize Instruction List
- [ ] Paging, Page Tables, and virtual addresses
    - [x] Define
    - [ ] Review
    - [ ] Finalize
- [ ] Interrupt and Exception Procedure
     - [ ]  Define
         - [x] Exception Numbers
         - [ ] Interrupt Procedures
     - [ ] Review
     - [ ] Finalize 
- [ ] Initialization Procedures
     - [x] CPU 0
     - [ ] Other CPUS
         - [x] Define
         - [ ] Review
         - [ ] Finalize 
- [ ] Changes Policy
     - [x] Define
     - [ ] Review
     - [ ] Finalize
  
Open Questions:
- [ ] Revisions vs. Extensions
    - [ ] When should changes be made to the Main ISA, vs. included in a new extension?
    - [ ] When should changes be made to existing extesions vs. a new extension?
    - [ ] Can extensions be eventually included in a later revision of the Main ISA?
- [ ] Memory Operations are currently all well-ordered. Is this potentially an issue performance-wise?

**Comment by chorman0773** [comment]
Issues blocking finalization
#12, #11, #10, #9, #8

**Comment by chorman0773** [comment]
Opinions on the open questions:
1. For changes to the main ISA, I'm am leaning towards saying "Never" or "Only to Fix bugs" (I-defect, I-spec-hole, and I-unclear issues). That is, once the main ISA is published in version 1.0, it will never have any material changes to it, and any changes must happen via a new extension.
2. Likewise, for extensions, I would say that once it's published in a minor release of the ISA, the extension is fixed and cannot be changed except for bug fixes, and new features need a whole new extension.
3. Given my position on question 1, I'd be hesistent to allow any extension to make it into the main document.
4. I do not believe that having well-ordered memory operations will cause a problem, as x86 and x86_64 also have this feature.
