### ISSUE TITLE
Tracking Issue: Floating Point Operations

### ISSUE THREAD

**Issue by chorman0773** [chorman0773/Clever-ISA#3]
This is an issue tracking the status of the floating-point operations extension

- [x] Floating-point Registers
- [ ] Instructions
     - [x]  Define
     - [ ] Review
     - [ ] Finalize
- [ ] Error Handling
     - [x] Define
     - [ ] Review
     - [ ] Finalize
    
Open Questions:
- [ ] Should Decimal Floating-point Operations be included or define in a future extension?
- [ ] Should the trig operations have dedicated instructions?
    - [ ] Precedent for Hardware-level trig functions
    - [ ] Difficult of implementation in hardware vs. software
- [ ]  Should there be an additional "total comparision" operation, or is integer comparison sufficient to trivially implement such in software?
